# Generated by Django 5.2.17 on 2026-09-16 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=120)),
                ('package', models.DecimalField(decimal_places=2, max_digits=7)),
                ('eligibility_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('eligible_departments', models.JSONField(default=list)),
                ('drive_date', models.DateField()),
                ('application_deadline', models.DateField()),
                ('required_skills', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='Upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='placement.company')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('year', models.PositiveSmallIntegerField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('skills', models.TextField(blank=True)),
                ('backlogs', models.PositiveIntegerField(default=0)),
                ('placement_status', models.CharField(default='Not Placed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=120)),
                ('package', models.DecimalField(decimal_places=2, max_digits=7)),
                ('placement_date', models.DateField()),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Placed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='placement.company')),
                ('placement_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='placement.placementdrive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='placement.student')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Applied', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placement.placementdrive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placement.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'placement_drive'), name='unique_student_drive')],
            },
        ),
    ]
